介绍了numpy中的切片和索引操作

In [1]:
import numpy as np

ndarray对象的内容可以通过索引或切片来访问和修改,ndarray 对象中的元素遵循基于零的索引。
有三种可用的索引方法类型： 字段访问，基本切片和高级索引。

### 切片

通过将 start，stop和step 参数提供给内置的 slice 函数来构造一个 Python slice 对象。
切片提供的是原始数据的视图，对视图修改会直接作用到原始数据上

#### 一维数组的切片

In [3]:
a = np.arange(10)
s = slice(2, 7, 2)   # python内置的slice切片对象
a[s]

array([2, 4, 6])

In [8]:
# 等效于直接切片
a[2:7:2]

array([2, 4, 6])

In [9]:
# 单个元素的切片
a[2]

2

In [10]:
# 定义初始切片点的切片
a[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

#### 多维数组的切片

In [32]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
# 第一个维度切片
b[1:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
# 第二个维度切片，可以用:和...表示某个维度的全量数据
print(b[:, :2])
print(b[..., :2])

[[0 1]
 [4 5]
 [8 9]]
[[0 1]
 [4 5]
 [8 9]]


In [33]:
# 修改视图印象原始数据
print("b的原始值为：{}".format(b))
b2 = b
b2[1][1] = 100
print("修改后b的值为:{}".format(b))

b的原始值为：[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
修改后b的值为:[[  0   1   2   3]
 [  4 100   6   7]
 [  8   9  10  11]]


### 2. 高级索引

高级索引返回原数据的视图，因此修改值也会影响原值

#### 数组索引

In [2]:
c = np.array([[1, 2], [3, 4], [5,6]])

In [3]:
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
c2 = c[[0,1,2], [0,1,0]]   # 返回数组中(0,0), (1,1), (2,2)处的元素
c2

array([1, 4, 5])

In [8]:
# 高级索引返回的是副本
c2[0] = 100
print(c)
print(c2)

[[1 2]
 [3 4]
 [5 6]]
[100   4   5]


In [2]:
d = np.arange(12).reshape(4,3)
d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [47]:
rows = np.array([[0,0], [3,3]])    
cols = np.array([[0,2], [0,2]])   # 索引为2*2维切片，所以返回二维数组，分别对应元素为(0,0),(0,2),(3,0),(3,2)
d[rows, cols]

array([[ 0,  2],
       [ 9, 11]])

In [48]:
rows = np.array([0,0,3,3])    
cols = np.array([[0,2,0,2]])   # 索引为1*2维切片，所以返回二维数组，分别对应元素为(0,0),(0,2),(3,0),(3,2)
d[rows, cols]

array([[ 0,  2,  9, 11]])

In [49]:
d[1:4, [1,2]]

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [4]:
# ix_参数为两个数组（对于2darray，参数为两个一维数组）
d[np.ix_([1,2], [2,1])]

array([[5, 4],
       [8, 7]])

In [5]:
# np.ix的返回值
np.ix_([1,2], [2,1])

(array([[1],
        [2]]), array([[2, 1]]))

#### 布尔索引

当结果对象是布尔运算（例如比较运算符）的结果时，将使用此类型的高级索引

In [50]:
e = np.arange(12).reshape(3,4)
e > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [53]:
# 大小对比
e[e>5]

array([ 6,  7,  8,  9, 10, 11])

In [59]:
# 取反
e[~(e>5)]

array([0, 1, 2, 3, 4, 5])

In [61]:
# 取反操作常用于过滤NaN
f = np.array([np.nan, 1, 2, np.nan,3,4,5])
f[~np.isnan(f)]

array([1., 2., 3., 4., 5.])

### 补充

In [62]:
# python内置的slice对象
# slice(start, stop, stride)
slice(1,5,2)

slice(1, 5, 2)

In [63]:
slice(None, None, 2)   # 不声明起始点和末尾点，只声明stride

slice(None, None, 2)

In [64]:
np.arange(12)[slice(None, None, 2)]   # 0、2、4...

array([ 0,  2,  4,  6,  8, 10])

In [70]:
# numpy内置了np.s_
print(np.arange(12)[np.s_[2]])     # 取第2个切片
print(np.arange(12)[np.s_[:2]] )    # 取开始到第二个
print(np.arange(12)[np.s_[2:5]] )    # 取第二个到第五个
print(np.arange(12)[np.s_[1:5:2]] )    # 取第一个到第五个，间隔2
print(np.arange(12)[np.s_[::2]] )    # 取从头到尾，间隔2

2
[0 1]
[2 3 4]
[1 3]
[ 0  2  4  6  8 10]


### 可变数量的索引

In [17]:
z = np.arange(27).reshape(3,3,3)
z

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [18]:
# 通过元组索引来进行选取，比如
indices = (1,1,1)
z[indices]

13

In [19]:
# 而通过列表的话，则无法实现变量的效果
z[1,1,1]   # 内部索引无法写成变量 

13

In [20]:
z[[1,1,1]]    # 写成这种则不是原来的目的

array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [21]:
# 对于多个，一样可以用元组
z[(1,1,slice(0,2))]

array([12, 13])