介绍了numpy中的算数运算

进行算数运算的数组必须有相同的shape或者符号广播机制

In [1]:
import numpy as np

In [2]:
a = np.arange(9).reshape(3,3)
b = np.array([10, 10, 10])
print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[10 10 10]


In [3]:
# 相加
np.add(a,b)   # 广播

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [4]:
# 相减
np.subtract(a, b)

array([[-10,  -9,  -8],
       [ -7,  -6,  -5],
       [ -4,  -3,  -2]])

In [5]:
# 相乘
np.multiply(a,b)

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

In [6]:
# 相除
np.divide(a, b)

array([[0. , 0.1, 0.2],
       [0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8]])

In [8]:
# 逐元素求倒数
a = np.array([0.1, 0.2, 0.25])
np.reciprocal(a)

array([10.,  5.,  4.])

In [9]:
# 逐元素求指数，第一个为底，第二个为幂次
a = np.array([1,2,3])
b = np.array([1,2,3])
np.power(a,b)

array([ 1,  4, 27])

In [10]:
# 逐元素求余数
a = np.array([5,7,9])
b = np.array([1,2,3])
np.mod(a, b)

array([0, 1, 0])