介绍了numpy中的矩阵操作

ndarray可以是任意维度，而matrix是一种特殊的ndarray，其必须为2维度

In [1]:
import numpy as np

### 1. ndarray和matrix的相互转换

In [6]:
# ndarray——>matrix  用 np.asmatrix或np.matrix
a = np.array([[1,2], [3,4]])
b = np.asmatrix(a)
c = np.matrix(a)
print(type(a))
print(type(b))
print(type(c))

<class 'numpy.ndarray'>
<class 'numpy.matrixlib.defmatrix.matrix'>
<class 'numpy.matrixlib.defmatrix.matrix'>


In [7]:
# matrix——>ndarray  用np.asarray或.A属性
a = np.matrix([[1,2], [3,4]])
b = np.asarray(a)
c = a.A
print(type(a))
print(type(b))
print(type(c))

<class 'numpy.matrixlib.defmatrix.matrix'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### 2. 矩阵生成

In [8]:
# 零矩阵
from numpy import matlib
matlib.zeros((2,2))

matrix([[0., 0.],
        [0., 0.]])

In [9]:
# 一矩阵
matlib.ones((2,2))

matrix([[1., 1.],
        [1., 1.]])

In [12]:
# 对角阵
# numpy.matlib.eye(n, M,k, dtype)
# n行数, M列数，k对角线的索引，dtype为数据类型
print(matlib.eye(n=3, M=4, k=0, dtype=float))   # 从第0个index开始对角
print(matlib.eye(n=3, M=4, k=1, dtype=float))   # 从第1个index开始对角
print(matlib.eye(n=3, M=4, k=2, dtype=float))   # 从第2个index开始对角

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [13]:
# 单位阵
matlib.identity(5, dtype=float)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [14]:
# 随机阵
matlib.rand(3,3)

matrix([[0.87644805, 0.33387423, 0.26548978],
        [0.33218347, 0.93466405, 0.49391335],
        [0.21229539, 0.71985156, 0.43265616]])

### 3. 矩阵运算

#### 3.1 行列式

In [15]:
# np.linalg.det
b = np.array([[6,1,1], [4, -2, 5], [2,8,7]])
np.linalg.det(b)

-306.0

#### 3.2 线性方程的解

In [16]:
# np.linalg.solve
A = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(A, b)
x

array([2., 3.])

In [17]:
# 检验是否计算正确
np.allclose(np.dot(A, x), b)    # 检验两个array的对应element是否在允许范围内接近

True

#### 3.3 逆矩阵

In [18]:
# np.linalg.inv
A = np.array([[3,1], [1,2]])
x = np.linalg.inv(A)
x 

array([[ 0.4, -0.2],
       [-0.2,  0.6]])

In [20]:
# 检验
np.allclose(np.dot(A,x), np.eye(2))

True