在Numpy中，矩阵是一种特殊的ndarray，即ndim为2，支持矩阵操作

In [1]:
import numpy as np

#### 构造矩阵和常见操作

In [7]:
# 构造矩阵
mat = np.matrix(np.random.randint(1, 9, (3,3)))
mat

matrix([[3, 3, 7],
        [5, 4, 4],
        [1, 6, 4]])

In [8]:
# 矩阵转置
mat.T

matrix([[3, 5, 1],
        [3, 4, 6],
        [7, 4, 4]])

In [9]:
# 逆矩阵
mat.I

matrix([[-0.07272727,  0.27272727, -0.14545455],
        [-0.14545455,  0.04545455,  0.20909091],
        [ 0.23636364, -0.13636364, -0.02727273]])

In [12]:
# 单位矩阵
A = np.eye(2)
A

array([[1., 0.],
       [0., 1.]])

In [13]:
# 全矩阵
B = np.full((2,2), 5)
B

array([[5, 5],
       [5, 5]])

In [14]:
# 两个矩阵相组合， 空格分列，；号分行
np.bmat("A B; A B")

matrix([[1., 0., 5., 5.],
        [0., 1., 5., 5.],
        [1., 0., 5., 5.],
        [0., 1., 5., 5.]])