Numpy中提供了concatenate,append,stack类(包括hsatck、vstack、dstack、row_stack、column_stack),r_和c_等类和函数用于数组拼接的操作。

In [2]:
import numpy as np

ar1 = np.array([[1,2,3], [4,5,6]])
ar2 = np.array([[7,8,9], [11,12,13]])

In [2]:
ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
ar2

array([[ 7,  8,  9],
       [11, 12, 13]])

### 1. np.concatenate()

In [ ]:
concatenate(a_tuple, axis=0, out=None)
"""
参数说明：
a_tuple:对需要合并的数组用元组的形式给出
axis: 沿指定的轴进行拼接，默认0，即第一个轴
"""

In [5]:
np.concatenate((ar1, ar2))   # 这里的第一轴是行方向

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [6]:
np.concatenate((ar1, ar2),axis=1)   # 这里沿第二个轴，即列方向进行拼接

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 11, 12, 13]])

In [7]:
# 一般进行concatenate操作的array的shape需要一致，当然如果array在拼接axis方向的size不一样，也可以完成
ar3 = np.array([[14,15,16]])
np.concatenate((ar1, ar3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [14, 15, 16]])

In [8]:
np.concatenate((ar1, ar3), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

### 2. pd.append()

In [ ]:
append(arr, values, axis=None)
"""
参数说明：
arr：array_like的数据
values: array_like的数据，若axis为None，则先将arr和values进行ravel扁平化,再拼接；否则values应当与arr的shape一致，或至多
        在拼接axis的方向不一致
axis：进行append操作的axis的方向，默认无
"""

In [10]:
np.append(ar1, ar2)    # 先ravel扁平化再拼接，所以返回值为一个1维数组

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [11]:
np.append(ar1, ar2, axis=0)     # 沿第一个轴拼接，这里为行的方向 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [12]:
np.append(ar1, ar2, axis=1)     # 沿第二个轴拼接，这里为列的方向 

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 11, 12, 13]])

### 3. np.stack()

In [ ]:
stack(arrays, axis=0, out=None)
"""
沿着指定的axis对arrays(每个array的shape必须一样)进行拼接，返回值的维度比原arrays的维度高1
axis：默认为0，即第一个轴，若为-1即为第二个轴
"""

In [13]:
np.stack((ar1, ar2))     # 增加第一个维度

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]])

In [14]:
np.stack((ar1, ar2), axis=1)   # 增加第二个维度

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [11, 12, 13]]])

In [15]:
np.stack((ar1, ar2), axis=-1)      # 增加第三个维度（在这个例子中，和axis=2效果一样）

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 11],
        [ 5, 12],
        [ 6, 13]]])

numpy中还提供了hsatck、vstack、dstack、row_stack、column_stack等操作进行数组的拼接

In [17]:
np.hstack((ar1,ar2))    # 水平拼接，沿着行的方向，对列进行拼接

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 11, 12, 13]])

In [18]:
np.vstack((ar1,ar2))    # 垂直拼接，沿着列的方向，对行进行拼接

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [3]:
np.dstack((ar1,ar2))    # 对于2维数组来说，沿着第三轴（深度方向）进行拼接

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 11],
        [ 5, 12],
        [ 6, 13]]])

In [19]:
np.column_stack((ar1,ar2))   # 水平拼接，沿着行的方向，对列进行拼接

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 11, 12, 13]])

In [21]:
np.row_stack((ar1,ar2))    # 垂直拼接，沿着列的方向，对行进行拼接

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

### 4. np.r_ 和np.c_

常用于快速生成array数据

In [22]:
np.r_[ar1,ar2]     # 垂直拼接，沿着列的方向，对行进行拼接

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [24]:
np.c_[ar1,ar2]   # 水平拼接，沿着行的方向，对列进行拼接

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 11, 12, 13]])