Numpy中的random模块整体功能类似于python的random模块，只是返回的为array数据

In [2]:
import numpy as np

1.元素数据位于0-1之间的array

In [3]:
np.random.rand(3,3)   # shape之间无须用元组表示

array([[0.926495  , 0.54815872, 0.89582301],
       [0.975755  , 0.34249179, 0.07443506],
       [0.95017396, 0.24356066, 0.81832258]])

In [8]:
np.random.random((3,3))    # shape之间用元组表示

array([[0.09052128, 0.47286779, 0.83693848],
       [0.29550694, 0.2530011 , 0.61444525],
       [0.26341722, 0.50859314, 0.35722373]])

In [10]:
np.random.rand()    # 同np.random.random(), 返回一个数（标量）

0.08757177145954209

2.元素数据符合正态分布的array

In [9]:
np.random.randn(3,3)

array([[ 1.37976187,  0.75649273, -0.83736669],
       [-2.18724745, -2.12669339,  0.3229381 ],
       [-1.49773565,  2.31032437,  0.96408579]])

3.元素为整数的array

In [23]:
# randint(low[, high, size]), 位于[low, high)左闭右开区间内，若为一个数，则为[0, low)
np.random.randint(2)   # 位于[0, 2)

0

In [24]:
np.random.randint(2, 8, size=10)

array([4, 5, 2, 2, 4, 7, 5, 6, 5, 7])

In [25]:
np.random.randint(2, 8, size=(3, 3))

array([[2, 5, 7],
       [7, 4, 2],
       [6, 5, 2]])

4.返回随机的浮点数,在半开区间 [0.0, 1.0)

In [26]:
# np.random中，sample=random=ranf
np.random.sample(4)

array([0.84758007, 0.24751027, 0.52951355, 0.9786592 ])

5.np.choice生成一个随机样本，从一个给定的一维数组

In [35]:
np.random.choice(np.arange(5),2)    # 有放回的取样

array([3, 3])

In [36]:
# 默认replace=True表示有放回，replace=False表示没有放回
np.random.choice(np.arange(5),size=(2,2), replace=False)    # 无放回的取样

array([[3, 2],
       [4, 1]])

In [41]:
# 参数p表示各值的采样权重，默认等权重
np.random.choice(5, 3, replace=False, p=[0.1, 0, 0.3, 0.6, 0])

array([2, 3, 0])

6.np.shuffle,对array进行序列的改变

In [37]:
A = np.arange(10)
np.random.shuffle(A)
print(A)

[0 1 8 7 3 2 4 5 6 9]


7.np.permutation返回一个随机排列

In [38]:
# 对单个整数，生成一个[0, N)的随机一维序列
np.random.permutation(10)

array([4, 1, 7, 9, 2, 0, 8, 3, 6, 5])

In [39]:
# 对一个一维数据，会做类似shuffle的操作
np.random.permutation(np.arange(10))

array([5, 4, 0, 2, 6, 8, 3, 1, 7, 9])

In [40]:
# 对于二维数组，会随机打乱其中的每个元素
np.random.permutation(np.arange(9).reshape(3,3))

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

8.随机数生成器

In [45]:
np.random.RandomState()     # 生成随机状态，类似于np.random.seed()
st = np.random.get_state()

In [46]:
np.random.choice(np.arange(10), 1)

array([5])

In [47]:
np.random.set_state(st)
np.random.choice(np.arange(10), 1)

array([5])