介绍了Numpy中与复制相关的函数

In [2]:
import numpy as np

### np.repeat

In [3]:
"""
repeat(a, repeats, axis=None)
逐元素（单个，或者某个轴上的一组数据）的复制
若axis不声明，对a做flat操作后进行repeat
"""
np.repeat(4, 3)

array([4, 4, 4])

In [4]:
# 不声明axis
np.repeat([[1,2],[3,4]],2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [5]:
# 按照行复制
np.repeat([[1,2],[3,4]],2, axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [6]:
# 按照列复制
np.repeat([[1,2],[3,4]],2, axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [7]:
# 对同一轴上的不同数据复制不同次数
np.repeat([[1,2],[3,4]],[2,3],axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

### np.tile

In [9]:
"""
tile(A, reps)
以原数据整体为组进行赋值
reps为array_like，表示沿各轴的复制次数，若reps的ndim小于A，则往前补1（即为broadcast操作）
某种意义上，tile可用来做广播操作，但实际如果要广播，建议用自带的broadcast函数
"""
np.tile(4, 3)

array([4, 4, 4])

In [10]:
a = np.array([0, 1, 2])

In [11]:
# 指定各axis的复制次数
np.tile(a, (2,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [13]:
# 指定轴ndim小于A的ndim，向前补1，凑成同shape
np.tile(a, (2,))    # 即为（1，2）

array([0, 1, 2, 0, 1, 2])

In [14]:
# 指定轴ndim大于A的ndim，同样做broadcast
np.tile(a, (2,2,2))

array([[[0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2]]])

### np.broad_to

In [16]:
"""
用于做广播操作
"""
x = np.array([1, 2, 3])
np.broadcast_to(x, (3,3,3))

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])