利用Numpy进行数组排序，同时执行其它相关任务

In [1]:
import numpy as np

In [4]:
A = np.random.randint(1, 10, size=5)
A

array([4, 5, 3, 7, 9])

从小值到大值进行排序，返回每个值对应的索引

In [5]:
A.argsort()

array([2, 0, 1, 3, 4])

In [6]:
# 返回A中从小到大的值，其返回值和sort类似，但sort为in—place操作
A[A.argsort()]

array([3, 4, 5, 7, 9])

按照原数组中元素的顺序，返回每个元素对应的排名

In [7]:
A.argsort().argsort()

array([1, 2, 0, 3, 4])

若要从大到小进行排序

In [8]:
A.argsort()[::-1]

array([4, 3, 1, 0, 2])

In [9]:
A[A.argsort()][::-1]

array([9, 7, 5, 4, 3])

#### 对于数组X，确定一组排列顺序；在对另一组数组Y中逐次进行选取

In [10]:
X = np.random.randint(1, 10, size=5)
X

array([6, 5, 8, 9, 4])

In [12]:
Y = np.random.randint(1, 10, size=5)
Y

array([2, 8, 4, 1, 9])

第一步：确定X中排列顺序索引

In [13]:
X.argsort().argsort()

array([2, 1, 3, 4, 0])

第二步：对Y进行排列，得到从小到大的序列

In [14]:
Y[Y.argsort()]

array([1, 2, 4, 8, 9])

第三步，按照X中排列顺序索引，对排序后的Y进行取值

In [15]:
Y[Y.argsort()][X.argsort().argsort()]

array([4, 2, 8, 9, 1])